In [1]:
import numpy as np

In [6]:
# 3.1

list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

arr = np.array(list)
arr_x4 = arr * 4
print(arr_x4)

mean_val = np.mean(arr)
print(mean_val)

median_val = np.median(arr)
print(median_val)

std_val = np.std(arr)
print(std_val)

min_index = np.argmin(arr)
max_index = np.argmax(arr)
print(min_index)
print(max_index)

print(arr[min_index])
print(arr[max_index])

min_val = np.min(arr)
max_val = np.max(arr)
print(min_val)
print(max_val)
# they match

greater_than_20 = arr[arr > 20]
print(greater_than_20)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]


In [9]:
# 3.2

matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

print(matrix.shape)
print(matrix.shape[0])
print(matrix.shape[1])

print(matrix[:, 2])

print(matrix[1])

matrix_x2 = matrix * 2
print(matrix_x2)

col_means = np.mean(matrix, axis=0)
print(col_means)

overall_mean = np.mean(matrix)
print(overall_mean)

row_max = np.max(matrix, axis=1)
print(row_max)

col_min = np.min(matrix, axis=0)
print(col_min)

flat = matrix.flatten()
print(flat)
print(flat.shape)
# It flattened the 2D array into 1D containing all elements in their row order.

min_index_flat = np.argmin(flat)
max_index_flat = np.argmax(flat)
print(min_index_flat)
print(max_index_flat)

min_coords = np.unravel_index(min_index_flat, matrix.shape)
max_coords = np.unravel_index(max_index_flat, matrix.shape)
print(min_coords)
print(max_coords)

greater_than_15 = matrix[matrix > 15]
print(greater_than_15)

sorted_matrix = np.sort(matrix, axis=1)
print(sorted_matrix)


(3, 4)
3
4
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [11]:
# 4

arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

rows_with_prime = []
for row in arr:
    if any(is_prime(x) for x in row):
        rows_with_prime.append(row)

rows_with_prime = np.array(rows_with_prime)

print(arr)
print(rows_with_prime)

[[ 2  3  5]
 [14  6  8]
 [11 13 17]
 [ 7 10 13]]
[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [13]:
# 5.1

def checkerboard_grid():
    return np.zeros((8, 8))

print(checkerboard_grid())

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
# 5.2 & 5.3

def checkerboard():
    board = np.zeros((8, 8))
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    return board

print(checkerboard())

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [15]:
# 5.4

def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, 1::2] = 1  
    board[1::2, ::2] = 1
    return board

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [16]:
# 6

def expansion(arr, n):
    space = " " * n
    expanded = [space.join(word) for word in arr]
    return np.array(expanded)

universe = np.array(['galaxy', 'clusters'])

print(expansion(universe, 1))

['g a l a x y' 'c l u s t e r s']


In [17]:
# 7

def second_brightest(stars):
    sorted_rows = np.sort(stars, axis=1)
    return sorted_rows[:, -2]

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)
print(second_brightest(stars))


[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
